line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "W", "UP"]

# Optional: tweak import sorting
[lint.isort]
force-sort-within-sections = true
known-first-party = ["custom_components", "simple_cover_service"]
