name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff
        run: ruff check .
      - name: hassfest
        uses: home-assistant/actions/hassfest@master
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "integration"
